const data = [
  {
    id: 1,
    itemImage: require('../assets/images/pent.png'),
    itemName: 'Mickey Mouseprint cardigan and jeans set',
    deliveryType: 'Free Delivery',
    price: 'Rp 479.000',
    leftItem: 'Only 1 left',
    orgPrice: 'Rp 899.000',
    bookmarkImage: require('../assets/images/bookmark.png'),
  },
  {
    id: 2,
    itemImage: require('../assets/images/pent.png'),
    itemName: 'Mickey Mouseprint cardigan and jeans set',
    deliveryType: 'Free Delivery',
    price: 'Rp 479.000',
    orgPrice: 'Rp 899.000',
    bookmarkImage: require('../assets/images/bookmark.png'),
  },
  {
    id: 3,
    itemImage: require('../assets/images/pent.png'),
    itemName: 'Mickey Mouseprint cardigan and jeans set',
    deliveryType: 'Free Delivery',
    soldOut: 'SOLD OUT',
    bookmarkImage: require('../assets/images/bookmark.png'),
  },
  {
    id: 4,
    itemImage: require('../assets/images/pent.png'),
    itemName: 'Mickey Mouseprint cardigan and jeans set',
    deliveryType: 'Free Delivery',
    shopIcon: require('../assets/images/shopImage.png'),
    price: 'Rp 479.000',
    orgPrice: 'Rp 899.000',
    bookmarkImage: require('../assets/images/bookmark.png'),
  },
  {
    id: 5,
    itemImage: require('../assets/images/pent.png'),
    itemName: 'Mickey Mouseprint cardigan and jeans set',
    deliveryType: 'Free Delivery',
    price: 'Rp 479.000',
    orgPrice: 'Rp 899.000',
    bookmarkImage: require('../assets/images/bookmark.png'),
  },
  {
    id: 6,
    itemImage: require('../assets/images/pent.png'),
    itemName: 'Mickey Mouseprint cardigan and jeans set',
    deliveryType: 'Free Delivery',
    price: 'Rp 479.000',
    orgPrice: 'Rp 899.000',
    bookmarkImage: require('../assets/images/bookmark.png'),
  },
];

export default data;
